#!/bin/bash

syntax_folder="${0%/*}/../src/syntax"
cd $syntax_folder
syntaxes=$(echo *.cc | sed 's/\.cc//g')

echo "#include \"syntax-lookup.h\""

echo "#include <map>"
echo "#include <string>"

for syntax in $syntaxes; do
	echo "#include \"syntax/$syntax.h\""
done

echo "std::map<std::string, Syntax*> SyntaxHighlighting::lookupMap;"
echo "void SyntaxHighlighting::initLookupMap() {"
for syntax in $syntaxes; do
	echo "    lookupMap[\"$syntax\"] = new ${syntax^^${syntax:0:1}}Syntax;"
done
echo "}"
echo "Syntax* SyntaxHighlighting::lookup(std::string key) {"
echo "    return lookupMap.at(key);"
echo "}"
echo "std::string SyntaxHighlighting::determineSyntax(Buffer *buffer) {"
echo "    for (auto syntax : lookupMap) {"
echo '      if (syntax.first == "generic") continue;'
echo "      if (syntax.second->matchFile(buffer)) return syntax.first;"
echo "    }"
echo '    return "generic";'
echo "}"
