state {
	root {
		pane {
			x: 0
			y: 0
			width: 2
			height: 2
		}
		tabsets {
			pane {
				x: 0
				y: 0
				width: 2
				height: 2
			}
			panesets {
				pane {
					x: 0
					y: 1
					width: 2
					height: 1
				}
				editors {
					pane {
						x: 0
						y: 1
						width: 2
						height: 1
					}
					buffer_path: "Untitled"
				}
			}
			panesets {
				pane {
					x: 0
					y: 1
					width: 2
					height: 1
				}
				editors {
					pane {
						x: 0
						y: 1
						width: 2
						height: 1
					}
					buffer_path: "Untitled2"
				}
			}
		}
	}
}
